package com.haibasoft.jobber.entities;
// Generated 01-Sep-2020 05:26:07 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Certifications generated by hbm2java
 */
@Entity
@Table(name = "certifications")
public class Certifications implements java.io.Serializable {

	private int id;
	private Jobseeker jobseeker;
	private String name;
	private String organisation;
	private Date issueDate;
	private Date expiryDate;
	private String credentialId;
	private String credentialUrl;

	public Certifications() {
	}

	public Certifications(int id, Jobseeker jobseeker) {
		this.id = id;
		this.jobseeker = jobseeker;
	}

	public Certifications(int id, Jobseeker jobseeker, String name, String organisation, Date issueDate,
			Date expiryDate, String credentialId, String credentialUrl) {
		this.id = id;
		this.jobseeker = jobseeker;
		this.name = name;
		this.organisation = organisation;
		this.issueDate = issueDate;
		this.expiryDate = expiryDate;
		this.credentialId = credentialId;
		this.credentialUrl = credentialUrl;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JobSeeker_id", nullable = false)
	@JsonBackReference(value = "jobseekercertification")
	public Jobseeker getJobseeker() {
		return this.jobseeker;
	}

	public void setJobseeker(Jobseeker jobseeker) {
		this.jobseeker = jobseeker;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "organisation", length = 254)
	public String getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(String organisation) {
		this.organisation = organisation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "issueDate", length = 19)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiryDate", length = 19)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "credentialId", length = 254)
	public String getCredentialId() {
		return this.credentialId;
	}

	public void setCredentialId(String credentialId) {
		this.credentialId = credentialId;
	}

	@Column(name = "credentialUrl", length = 254)
	public String getCredentialUrl() {
		return this.credentialUrl;
	}

	public void setCredentialUrl(String credentialUrl) {
		this.credentialUrl = credentialUrl;
	}

}
