package com.haibasoft.jobber.entities;
// Generated 01-Sep-2020 05:26:07 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Company implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private String logo;
	private Set<Recruiter> recruiters = new HashSet<Recruiter>(0);

	public Company() {
	}

	public Company(int id) {
		this.id = id;
	}

	public Company(int id, String name, String description, String logo, Set<Recruiter> recruiters) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.logo = logo;
		this.recruiters = recruiters;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "logo", length = 254)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@OneToMany(mappedBy = "company")
	@JsonManagedReference(value = "companyrecruiter")
	public Set<Recruiter> getRecruiters() {
		return this.recruiters;
	}

	public void setRecruiters(Set<Recruiter> recruiters) {
		this.recruiters = recruiters;
	}

}
