package com.haibasoft.jobber.entities;
// Generated 01-Sep-2020 05:26:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Languagespoken generated by hbm2java
 */
@Entity
@Table(name = "languagespoken")
public class Languagespoken implements java.io.Serializable {

	private LanguagespokenId id;
	private Jobseeker jobseeker;
	private Language language;
	private String languagelevel;

	public Languagespoken() {
	}

	public Languagespoken(LanguagespokenId id, Jobseeker jobseeker, Language language) {
		this.id = id;
		this.jobseeker = jobseeker;
		this.language = language;
	}

	public Languagespoken(LanguagespokenId id, Jobseeker jobseeker, Language language, String languagelevel) {
		this.id = id;
		this.jobseeker = jobseeker;
		this.language = language;
		this.languagelevel = languagelevel;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "languageId", column = @Column(name = "Language_id", nullable = false)),
			@AttributeOverride(name = "jobSeekerId", column = @Column(name = "JobSeeker_id", nullable = false, length = 64)) })
	public LanguagespokenId getId() {
		return this.id;
	}

	public void setId(LanguagespokenId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JobSeeker_id", nullable = false, insertable = false, updatable = false)
	@JsonBackReference(value = "languagespokenjobseeker")
	public Jobseeker getJobseeker() {
		return this.jobseeker;
	}

	public void setJobseeker(Jobseeker jobseeker) {
		this.jobseeker = jobseeker;
	}
	
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Language_id", nullable = false, insertable = false, updatable = false)
	@JsonBackReference(value = "languagespoken")
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "languagelevel", length = 254)
	public String getLanguagelevel() {
		return this.languagelevel;
	}

	public void setLanguagelevel(String languagelevel) {
		this.languagelevel = languagelevel;
	}

}
