package com.haibasoft.jobber.entities;
// Generated 01-Sep-2020 05:26:07 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language implements java.io.Serializable {

	private int id;
	private String languageName;
	private Set<Languagespoken> languagespokens = new HashSet<Languagespoken>(0);

	public Language() {
	}

	public Language(int id) {
		this.id = id;
	}

	public Language(int id, String languageName, Set<Languagespoken> languagespokens) {
		this.id = id;
		this.languageName = languageName;
		this.languagespokens = languagespokens;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "languageName", length = 254)
	public String getLanguageName() {
		return this.languageName;
	}

	public void setLanguageName(String languageName) {
		this.languageName = languageName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	@JsonManagedReference(value = "languagespoken")
	public Set<Languagespoken> getLanguagespokens() {
		return this.languagespokens;
	}

	public void setLanguagespokens(Set<Languagespoken> languagespokens) {
		this.languagespokens = languagespokens;
	}

}
