package com.haibasoft.jobber.entities;
// Generated 01-Sep-2020 05:26:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LanguagespokenId generated by hbm2java
 */
@Embeddable
public class LanguagespokenId implements java.io.Serializable {

	private int languageId;
	private String jobSeekerId;

	public LanguagespokenId() {
	}

	public LanguagespokenId(int languageId, String jobSeekerId) {
		this.languageId = languageId;
		this.jobSeekerId = jobSeekerId;
	}

	@Column(name = "Language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "JobSeeker_id", nullable = false, length = 64)
	public String getJobSeekerId() {
		return this.jobSeekerId;
	}

	public void setJobSeekerId(String jobSeekerId) {
		this.jobSeekerId = jobSeekerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LanguagespokenId))
			return false;
		LanguagespokenId castOther = (LanguagespokenId) other;

		return (this.getLanguageId() == castOther.getLanguageId())
				&& ((this.getJobSeekerId() == castOther.getJobSeekerId())
						|| (this.getJobSeekerId() != null && castOther.getJobSeekerId() != null
								&& this.getJobSeekerId().equals(castOther.getJobSeekerId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLanguageId();
		result = 37 * result + (getJobSeekerId() == null ? 0 : this.getJobSeekerId().hashCode());
		return result;
	}

}
